### PR TITLE
GTK3 port 

### PR DESCRIPTION
**Pull request by alexandrucosminmihai**

### CODE REVIEW

**Comment by amanharitsh123** [comment]
`gi.require_version('Gtk', '3.0')` include this line , otherwise an unnecessary warning will be raised in the logs.

**Comment by alexandrucosminmihai** [comment]
You're right. Done

**Comment by yell0wfl4sh** [comment]
@alexandrucosminmihai Delete ```.pyc``` files, and add a suitable ```.gitignore``` file to avoid adding any temporary files in future.  You can find a sample ```.gitignore``` file [here](https://github.com/sugarlabs/buttons-and-scissors-activity/blob/master/.gitignore).

**Comment by alexandrucosminmihai** [comment]
Updated my pull request. Thank you!

**Comment by quozl** [comment]
Too much change visible in lines that seem not to have changes; can you check to see if you changed tabs to spaces or vice versa?  Specifically lines 47 to 127 of activity.py, click on "files changed" tab on pull request to see.

**Comment by alexandrucosminmihai** [comment]
I did change spaces to tabs with my IDE. Should I convert them back?

**Review by yell0wfl4sh — CHANGES_REQUESTED** [review]
You have wrong indentation from line 41. Test your changes thoroughly before committing it.

**Comment by quozl** [comment]
It's okay to change spacing, but not when you need review of changes that aren't spacing.  Agree with @yashagrawal3 that 2d53e4e is worse.  Use "git diff origin/master" repeatedly until you understand each change you've made.

**Comment by alexandrucosminmihai** [comment]
Sorry about that.

**Comment by quozl** [comment]
Reviewed.  Pass.  As others are involved, will wait for consensus before merging.

**Comment by alexandrucosminmihai** [comment]
Great! Thank you for your time and sorry for my missteps!

**Review by yell0wfl4sh — APPROVED** [review]
Looks good. Pass from me too. Just a suggestion for future, try squashing commits that were made to improve your mistakes in previous commits of the PR. It saves time and effort of the person merging it.

**Comment by quozl** [comment]
@yashagrawal3, yes, that's true, but it's extra work that I'd require for the toolkit and shell, but not for a small activity like this.  Whoever takes responsibility of closure can choose whether to merge, rebase, squash, or simply cherry-pick and commit.  Given the patches as they stand, I would squash as my act of closure, so there's no need for you to do it right now @alexandrucosminmihai.  Also that we are all responding fairly quickly means we have kept memory of change in mind.  Different when a pull request lives over many days.

**Comment by yell0wfl4sh** [comment]
@quozl True!

**Comment by alexandrucosminmihai** [comment]
I will be careful to pay more attention to this aspect in the future. Thank you both for your guidance!

**Pull request merged**
