### PR TITLE
flake8

### PR DESCRIPTION
**Pull request by ayushnawal**
@quozl

### CODE REVIEW

**Comment by srevinsaju** [comment]
@ayushnawal If you could rebase the commits, it would be easier for @quozl to merge the commits. Thanks

**Comment by ayushnawal** [comment]
Thanks, @srevinsaju for the review.

are you asking to rebase it with the `font` branch?

it is already up to date with the `master` branch.

**Comment by srevinsaju** [comment]
I meant tidy up the commits, like the first and the last commits into one single commits flake8 fixes

**Comment by quozl** [comment]
I agree, it would be easier.  If you're not sure, just look at commits in history.

**Pull request merged**
